'use strict';

const fs = require('fs');
const DB = require('core/db');
const FORMATTERS = require('tables/formatters');

exports.getAsObject = tableName => {
    const sql = fs.readFileSync(`tables/sql/${tableName}.sql`, 'utf8');

    return DB.then(conn => conn.execute(sql))
        .then(([rows, fields]) => {
            const config = require(`tables/configs/${tableName}.json`);

            let table = {
                cols: [],
                rows: [],
            };

            //prepare cols for frontend
            for (const col of config) {
                let frontendCol = {};

                const frontendAllowed = ['name', 'title', 'defaultContent', 'sortOrder', 'sortDirection', 'frontendFormatter'];
                for (const key of frontendAllowed) {
                    if (col[key] !== undefined) {
                        frontendCol[key] = key === 'frontendFormatter' ? FORMATTERS[col[key]] : col[key];
                    }
                }

                table.cols.push(frontendCol);
            }

            //prepare rows for frontend
            for (const row of rows) {
                const frontendRow = {};

                for (const col of config) {
                    if (col.hasOwnProperty('backendFormatter')) {
                        const formatter = FORMATTERS[col.backendFormatter[0]];
                        const params = col.backendFormatter.slice(1);
                        //formatter can't use values generated by other formatters
                        frontendRow[col.name] = formatter.f(...params)(row);
                    } else {
                        frontendRow[col.name] = row[col.name];
                    }
                }

                table.rows.push(frontendRow);
            }
                        console.log(table.cols);
            return table;
        });
}
