AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example RESTful service
Resources:
  ABLambdaRouter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      Events:
        ABAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any